languageCode = "en-us"
title = "DOP Deploment Orchestrator for Puppet"
baseurl = "https://swisscom.github.io/docs-dop/"

themesdir = "themes"
theme = "hugo-theme-learn"

publishDir='docs'

[params]
  # Activate search. Don't forget to generate the JSON index file (go check get started page)
  search = true
